[package]
name = "my-redis"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = true
opt-level = 0
debug-assertions = true
overflow-checks = true

[dependencies]
bytes = "1.9.0"
color-backtrace = "0.6.1"
mini-redis = "0.4.1"
tokio = "1.41.1"
